services:
  db:
    image: pgvector/pgvector:pg15
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: ragtalk
      POSTGRES_PASSWORD: ragtalk
      POSTGRES_DB: ragtalk
    volumes:
       - ./data/db:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-d", "ragtalk", "-U", "ragtalk"]
      interval: 10s
      timeout: 5s
      retries: 5

  api:
    build: .
    ports:
      - '3000:8080'
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env
    volumes:
      - ./src:/app